WIDTH = 540
HEIGHT = 960
FPS = 60

ARENA_SIZE = 480

ARENA_LEFT = (WIDTH - ARENA_SIZE) // 2
ARENA_RIGHT = ARENA_LEFT + ARENA_SIZE
ARENA_TOP = (HEIGHT - ARENA_SIZE) // 2
ARENA_BOTTOM = ARENA_TOP + ARENA_SIZE

HERO_RADIUS = 30
BOSS_RADIUS = 65

HERO_MASS = 1
BOSS_MASS = 12

MAX_HERO_SPEED = 5
MAX_BOSS_SPEED = 3

FRICTION = 0.9998

IMPACT_BOOST = 1.12
REPULSION_FORCE = 0.6

COLLISION_COOLDOWN = 120
SPAWN_IMMUNITY = 150